<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook form_user_login_form_alter.
 * 
 * @param mixed $form
 *   The form object.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The current form state.
 * @param mixed $form_id
 *   The id of the form.
 */
function custom_blocks_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'custom_blocks_user_login_form_submit';
}

/**
 * Implements hook user_login_form_submit.
 * Custom submit handler for the login form.
 * 
 * @param mixed $form
 *   The form object.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The current form state.
 */
function custom_blocks_user_login_form_submit($form, FormStateInterface $form_state) {
  // Url object from the route.
  $url = Url::fromRoute('custom_blocks.content');
  // Setting the redirecct url.
  $form_state->setRedirectUrl($url);
}

/**
 * Implements hook theme.
 * 
 * @param mixed $existing
 *   Array of existing implementations.
 * @param mixed $type
 *   Type of theme-actual theme or parent theme.
 * @param mixed $theme
 *   The name of the theme.
 * @param mixed $path
 *   The directory path of theme.
 *
 * @return array[]
 *   Associative array of theme hook information.
 */
function custom_blocks_theme($existing, $type, $theme, $path) {
  return [
    'my_custom_block' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}
