<?php

/**
 * Implements hook theme.
 * 
 * @param mixed $existing
 *   Array of existing implementations.
 * @param mixed $type
 *   Type of theme-actual theme or parent theme.
 * @param mixed $theme
 *   The name of the theme.
 * @param mixed $path
 *   The directory path of theme.
 *
 * @return array[]
 *   Associative array of theme hook information.
 */
function database_operations_theme($existing, $type, $theme, $path) {
  return [
    'events_data' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}
